services:
  frontend:
    build:
      dockerfile: './apps/frontend/Dockerfile'

    ports:
      - "80:80"

    depends_on:
      - backend

  backend:
    build:
      dockerfile: './apps/api/Dockerfile'
    
    expose:
      - 3333