services:
  frontend:
    build: ./apps/frontend

    ports:
      - "8080:80"

    environment:
      - NX_PUBLIC_API_URL=backend

    depends_on:
      - backend

  backend:
    build: ./apps/api

    ports:
      - "3333:3333"